Feature/wav2vec2 updates
huggingface/optimum-graphcore pull request #123
Opened 2022-07-13 13:27 UTC by thorinf

# What does this PR do?

Additions:
- Fine-tuning of wav2vec2 added.
- Inference of wav2vec2 added.

Fixes/Improvements to Pre-training:
- Gumbel temp uses callback, same as Transformers examples, instead of computing in data-loader. Data-loader just uses the value updated in the callback.
- Tensor reduction! Both data-loader and model have been modified to reduce the tensor size going into GS-VQ and loss to minimise the number of unmasked indexes being included. Unmasked indices do not contribute to pre-training loss and are redundant. This significantly improves memory.
- Evaluation will run and log loss.
- GS-VQ computes BOTH perplexities regardless of train/eval setting. This is fairseq (original implementation) performs it.
- Parallelise method is modified. Some layers have been added for assignment, and doesn't allow user to pipeline without correct layer numbers.

Fixes # (issue)

## Before submitting
- [N] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [Y] Did you make sure to update the documentation with your changes?
- [N] Did you write any new necessary tests?

2022-07-25 13:57 UTC, jimypbr requested changes

2022-07-25 13:57 UTC, jimypbr commented on examples/speech-pretraining/run_pretraining.py
>  check_min_version("4.15.0.dev0")
min version and required version have different versions

2022-07-25 13:57 UTC, jimypbr commented on examples/speech-recognition/large_8-ipu_config.json
> +{
is this used? can delete or move to hf hub?

2022-07-25 13:57 UTC, jimypbr commented on examples/speech-recognition/base_4-ipu_config.json
> +{
is this used? can delete or move to hf hub?

2022-07-25 14:21 UTC, jimypbr commented on examples/speech-recognition/large_8-ipu_config.json
> +{
> Could you put the IPUConfig jsons on the graphcore org on the HF hub please?

Sorry. I remember that you have PRs on the HF Hub to update the configs. I guess you will delete these before merge?

2022-07-25 16:39 UTC, michaelbenayoun reviewed
Thanks a lot for this huge contribution!
I left a few comments. 
Also quick question: can you check your code formatter? I think the max length allowed is set to 80 for you, which reformats a lot of the code... you should use the configuration we have:
- `setup.cfg`
- `pyproject.toml`

2022-07-25 16:39 UTC, michaelbenayoun commented on examples/speech-pretraining/base_4-ipu_config.json
> +{
If this is validated, I think it'll be better to put it on the Hub instead of having it as a file in the examples.

2022-07-25 16:39 UTC, michaelbenayoun commented on examples/speech-pretraining/large_8-ipu_config.json
> +{
Same comment as above.

2022-07-25 16:39 UTC, michaelbenayoun commented on examples/speech-pretraining/requirements.txt
> +wandb
Why?

2022-07-25 16:39 UTC, michaelbenayoun commented on examples/speech-pretraining/run_pretraining.py
> +    "transformers==4.18.0",
Do you really require this?

2022-07-25 16:39 UTC, michaelbenayoun commented on examples/speech-pretraining/run_pretraining.py
> +        batch["sampled_negative_indices"] = torch.tensor(
Cant we make things directly in pytorch instead of using numpy? Dont know if this is relevant, but asking!

2022-07-25 16:39 UTC, michaelbenayoun commented on examples/speech-recognition/requirements.txt
> +wandb
Why?

2022-07-25 16:39 UTC, michaelbenayoun commented on examples/speech-recognition/requirements.txt
> +transformers==4.18.0
Why?

2022-07-25 16:39 UTC, michaelbenayoun commented on examples/speech-recognition/run_inference_ctc.py
> +check_min_version("4.15.0.dev0")
Why? Not matching with the requirements.

2022-07-25 16:39 UTC, michaelbenayoun commented on examples/speech-recognition/run_speech_recognition_ctc.py
> +check_min_version("4.15.0.dev0")
Why? Not matching with the requirements.

2022-07-26 09:19 UTC, jimypbr commented on examples/speech-pretraining/README.md
>  	--max_duration_in_seconds 20.0 \
should  be 15.6 seconds for base

2022-07-27 12:57 UTC, thorinf commented
Changes made, I'll also push configs to model-hub

2022-07-27 13:12 UTC, jimypbr approved these changes

2022-07-27 13:16 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-graphcore/pr_123). All of your documentation changes will be reflected on that endpoint.

2022-07-29 15:46 UTC, merged