Run encoder on IPU for encoder-decoder text-gen models
huggingface/optimum-graphcore pull request #283
Opened 2023-03-14 20:41 UTC by jimypbr

# What does this PR do?

Optimisation for encoder/decoder text-gen models that runs the encoder part of the model on IPU instead of CPU.
It does this by automatically splitting the IPUConfig into two different configs for the encoder and decoder based upon the `ipu_config.layers_per_ipu` and the corresponding `config.num_layers` and `config.num_decoder_layers` from the model.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2023-03-14 20:45 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-graphcore/pr_283). All of your documentation changes will be reflected on that endpoint.

2023-03-17 17:11 UTC, HMellor commented on optimum/graphcore/modeling_utils.py
> +        if isinstance(ipu_config.layers_per_ipu, list):
If the user passes an integer, do we put it into a list?

2023-03-17 17:12 UTC, HMellor commented on optimum/graphcore/modeling_utils.py
> +    msg = (
Is this comment in the right place? I'm not sure I follow

2023-03-18 09:55 UTC, HMellor requested changes

2023-03-18 09:55 UTC, HMellor commented on tests/test_ipu_configuration.py
> +    def test_split_encoder_decoder_ipu_config(self):
All the tests are good, less keen that they are all in one monolithic test.

Splitting them up and [grouping them in a class](https://docs.pytest.org/en/7.1.x/getting-started.html#group-multiple-tests-in-a-class) would be good.

2023-03-18 09:55 UTC, HMellor commented on optimum/graphcore/generation_utils.py
> +        if not hasattr(self, "poptorch_encoder"):
Can you either use this in both places or use `x_ipu_config = getattr(self, "x_ipu_config", self.ipu_config)` in both places like you did for the decoder?

2023-03-18 09:55 UTC, HMellor commented on optimum/graphcore/generation_utils.py
> +import copy
Doesn't look like this is used based on the diff

2023-03-18 09:55 UTC, HMellor commented on optimum/graphcore/generation_utils.py
> +from itertools import groupby
No longer used

2023-03-18 09:55 UTC, HMellor commented on optimum/graphcore/generation_utils.py
> +    def detachFromDevice(self):
Will this cause problems if a pipeline is created with a non split model? Or is this class only used for split models?

2023-03-18 09:55 UTC, HMellor commented on optimum/graphcore/modeling_utils.py
> +            return [target_number_of_layers]
Good catch

2023-03-18 09:55 UTC, HMellor commented on optimum/graphcore/modeling_utils.py
> +    cumsum = [sum(layers_per_ipu[: i + 1]) for i in range(len(layers_per_ipu))]
What happens if there's a `0` at the cut?

i.e. if we had `[1, 2, 3, 0, 5, 6, 7, 8]` would it get split into `[1, 2, 3]` and `[0, 5, 6, 7, 8]`?

2023-03-20 10:46 UTC, jimypbr commented on optimum/graphcore/generation_utils.py
> +        if not hasattr(self, "poptorch_encoder"):
The decoder one is a special case that needs that check because models like GPT are decoder-only

2023-03-20 10:50 UTC, jimypbr commented on optimum/graphcore/generation_utils.py
> +    def detachFromDevice(self):
This might cause problems if the model is being used like in training mode in the `IPUTrainer`.

2023-03-20 10:52 UTC, jimypbr commented on optimum/graphcore/modeling_utils.py
> +    cumsum = [sum(layers_per_ipu[: i + 1]) for i in range(len(layers_per_ipu))]
Good catch!

2023-03-20 11:03 UTC, HMellor commented on tests/test_ipu_configuration.py
> +    def test_split_encoder_decoder_ipu_config(self):
I think I'll do this in a separate PR to make this change on other tests too (if I feel it's worth it)

2023-03-20 11:05 UTC, HMellor commented on optimum/graphcore/generation_utils.py
> +    def detachFromDevice(self):
I suppose if the model isn't split it'll just be a no-op, but we'd like it to work for all possible poplar executors that can exist in generation

2023-03-20 13:48 UTC, jimypbr commented on optimum/graphcore/pipelines/__init__.py
> +            model.parallelize()
No the `is_encoder_decoder` is a taxonomy of the model and doesn't change at run time. We need a `for_generation` so we can run encoder-decoder models in either "training mode" (encoder and decoder in same executor) or in generation mode.

2023-03-20 14:56 UTC, HMellor commented on optimum/graphcore/generation_utils.py
> +from .modeling_utils import get_layer_ipu
Not used here?
```suggestion
```

2023-03-20 14:56 UTC, HMellor commented on optimum/graphcore/generation_utils.py
> +    def detachFromDevice(self):
Did you check this?

2023-03-20 15:40 UTC, HMellor commented on optimum/graphcore/modeling_utils.py
> +        raise IncompatibleIPUConfigError("Invalid values in layers_per_ipu. " f"layers_per_ipu={layers_per_ipu}")
```suggestion
        raise IncompatibleIPUConfigError(f"Invalid values in layers_per_ipu. layers_per_ipu={layers_per_ipu}")
```

2023-03-20 18:21 UTC, merged