Bart
huggingface/optimum-graphcore pull request #30
Opened 2022-02-02 10:26 UTC by michaelbenayoun

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2022-02-04 10:42 UTC, jimypbr commented on optimum/graphcore/modeling_utils.py
> +    module.register_forward_hook(recompute_outputs)
return this hook so we can register it in `self._hooks`

2022-02-04 17:10 UTC, michaelbenayoun commented on optimum/graphcore/modeling_utils.py
> +    module.register_forward_hook(recompute_outputs)
Done!

2022-02-04 17:10 UTC, michaelbenayoun commented on optimum/graphcore/modeling_utils.py
> +    module.register_forward_hook(disable)
Done!

2022-02-25 12:42 UTC, jimypbr commented on optimum/graphcore/trainer.py
> +                    # "max_grad_norm": self.args.max_grad_norm,
Remove this?

2022-02-25 12:44 UTC, jimypbr commented on optimum/graphcore/trainer.py
> +                    # "max_grad_norm": self.args.max_grad_norm,
Remove this?

2022-02-25 12:46 UTC, jimypbr commented on optimum/graphcore/trainer.py
> +            # optimizer_kwargs["weight_decay"] = 0
remove this?

2022-02-25 12:48 UTC, jimypbr commented on optimum/graphcore/trainer_seq2seq.py
> +        # XXX: adapt synced_gpus for fairscale as well
comment not relevant here?

2022-02-25 12:50 UTC, jimypbr commented on optimum/graphcore/trainer_seq2seq.py
> +                outputs = model(**inputs)
Is this running on CPU only?

2022-02-25 12:54 UTC, jimypbr requested changes
Looks great!
Please add a README to the Bart and T5 examples with instructions on how to run things.

2022-02-25 13:21 UTC, michaelbenayoun commented on optimum/graphcore/trainer.py
> +                    # "max_grad_norm": self.args.max_grad_norm,
I would love to keep this because it can help training in fp16, but this was making the tests fail, do you have any idea?

2022-02-25 13:22 UTC, michaelbenayoun commented on optimum/graphcore/trainer.py
> +            # optimizer_kwargs["weight_decay"] = 0
Yes, I think it should be removed, thanks.

2022-02-25 15:22 UTC, michaelbenayoun commented on optimum/graphcore/trainer_seq2seq.py
> +                outputs = model(**inputs)
I think we should not focus on this part yet, as generation related features will come in another pr.

2022-02-25 15:26 UTC, jimypbr commented on optimum/graphcore/trainer.py
> +                    # "max_grad_norm": self.args.max_grad_norm,
Ok I've not used this option before. Let's keep it as a comment

2022-02-25 15:28 UTC, jimypbr approved these changes

2022-02-25 15:28 UTC, jimypbr commented
🎉 looks good to me

2022-02-25 16:36 UTC, merged