Add Flan-T5 notebook
huggingface/optimum-graphcore pull request #318
Opened 2023-04-12 13:33 UTC by HMellor

# What does this PR do?

Adds a notebook example for Flan-T5

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2023-04-12 13:36 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-graphcore/pr_318). All of your documentation changes will be reflected on that endpoint.

2023-04-14 05:16 UTC, jayniep-gc requested changes
Most of these are minor phrasing improvements to make the text clearer.

2023-04-14 05:16 UTC, jayniep-gc commented on notebooks/flan_t5_inference.ipynb
> +    "text_classification_1 = \"\"\"Message: When the spaceship landed on Mars, the whole humanity was excited\n",
```suggestion
    "text_classification_1 = \"\"\"Message: When the spaceship landed on Mars, the whole of humanity was excited\n",
```

2023-04-14 05:16 UTC, jayniep-gc commented on notebooks/flan_t5_inference.ipynb
> +    "As we saw earlier when looking at the results from the paper, Flan-T5-XL is roughly 40% better than Flan-T5-Large on average across its validation tasks. Therefore when deciding if Flan-T5-XL is
```suggestion
    "As we saw earlier when looking at the results from the paper, Flan-T5-XL is roughly 40% (on average) better than Flan-T5-Large across its validation tasks. Therefore when deciding if Flan-T5-XL is worth the cost for you, ask yourself the following questions:\n",
```

2023-04-14 05:16 UTC, jayniep-gc commented on notebooks/flan_t5_inference.ipynb
> +    "For fun, let's now look at an example of a task where the answer to all of the above questions is yes. Let's say you have a customer service AI that you use to answer basic questions in order to
```suggestion
    "To demonstrate, let's now look at an example of a task where the answer to all of the above questions is yes. Let's say you have a customer service AI that you use to answer basic questions in order to reduce the workload of your customer service personnel. This needs:\n",
```

2023-04-14 05:16 UTC, jayniep-gc commented on notebooks/flan_t5_inference.ipynb
> +    "- Strong linguistic ability to both parse and generate meduim sized chunks of text\n",
```suggestion
    "- Strong linguistic ability to both parse and generate medium-sized chunks of text\n",
```

2023-04-14 05:16 UTC, jayniep-gc commented on notebooks/flan_t5_inference.ipynb
> +    "- The ability to produce multiple sentence responses, but not much longer than this\n",
```suggestion
    "- The ability to produce multiple-sentence responses, but not much longer than this\n",
```

2023-04-14 05:16 UTC, jayniep-gc commented on notebooks/flan_t5_inference.ipynb
> +    "Looking at the code below, we see some context about Graphcore provided in the input, as well as primer for a conversational response from the model. As you can see from the example conversation
```suggestion
    "Looking at the code below, we see some context about Graphcore provided in the input, as well as a primer for a conversational response from the model. As you can see from the example conversation (read the example conversation before executing the code block), Flan-T5-XL was able to understand the information provided in the context and provide useful and natural answers to the questions it was asked."
```

2023-04-14 05:16 UTC, jayniep-gc commented on notebooks/flan_t5_inference.ipynb
> +      "[Virtual Assistant]: The Intelligence Processing Unit (IPU) is a computer chip that is used to process artificial intelligence.\n",
```suggestion
      "[Virtual Assistant]: The intelligence processing unit (IPU) is a computer chip that is used to process artificial intelligence applications.\n",
```

2023-04-14 05:16 UTC, jayniep-gc commented on notebooks/flan_t5_inference.ipynb
> +    "The [virtual assistant] works at Graphcore. Graphcore is:\n",
The following text does not all fit the opening "Graphcore is". I don't fully understand how clear these statements need to be for the model to understand, but I would update the statements as follows so that they are all clear (unless your example is intended to demonstrate how good the model is that it can parse even poorly constructed input!):
- Graphcore is located in Bristol.
- Graphcore invented the intelligence processing unit (IPU). It is purpose built for AI applications.
- The currently available IPU models are: Classic IPU, Bow IPU, C600.
- IPUs are available on: Paperspace, Gcore Cloud and Graphcloud.

2023-04-14 05:16 UTC, jayniep-gc commented on notebooks/flan_t5_inference.ipynb
> +}
A conclusion is missing to tie up what you've presented and to give the user some next steps.

2023-04-14 08:39 UTC, HMellor commented on notebooks/flan_t5_inference.ipynb
> +    "- GPT-3 must be finetuned for MMLU to rank at the top of this comparison, but this benchmark was held out for evaluation with Flan-T5\n",
MMLU is the benchmark so I'm not sure about the current suggested change as it makes MMLU the subject of the clause.

2023-04-14 08:45 UTC, HMellor commented on notebooks/flan_t5_inference.ipynb
> +    "# TODO remove when configs are uploaded to HF\n",
No this is for me, this code is needed for the notebook to work. Once the two PRs mentioned in this PR's description are merged, I can act on this TODO

2023-04-14 08:46 UTC, HMellor commented on notebooks/flan_t5_inference.ipynb
> +    "    \"Review: Wasn't that impressed, went back to my old phone. Sentiment:\"\n",
Leaving the answer blank is how we prompt the model for the answer. So you can consider the first 3 reviews to be k=3 "shots" and the final review to be the actual prompt

2023-04-14 08:50 UTC, HMellor commented on notebooks/flan_t5_inference.ipynb
> +    "The [virtual assistant] works at Graphcore. Graphcore is:\n",
No you're right this is just a poorly constructed input. I'll clean it up with your suggestion

2023-04-14 09:04 UTC, jayniep-gc commented on notebooks/flan_t5_inference.ipynb
> +    "- GPT-3 must be finetuned for MMLU to rank at the top of this comparison, but this benchmark was held out for evaluation with Flan-T5\n",
I think understanding what you mean by "held out" might help me propose a better change.

2023-04-14 09:17 UTC, HMellor commented on notebooks/flan_t5_inference.ipynb
> +    "- GPT-3 must be finetuned for MMLU to rank at the top of this comparison, but this benchmark was held out for evaluation with Flan-T5\n",
"held out" in this context means that it was not used in training. So all the tasks in MMLU have not been seen before by Flan-T5

2023-04-14 11:48 UTC, jayniep-gc commented on notebooks/flan_t5_inference.ipynb
> +    "    - A: For an approximately 40% performance increase over Flan-T5-Large, enabling more demanding tasks.\n",
```suggestion
    "    - A: For an approximately 40% performance increase over Flan-T5-L, enabling more demanding tasks.\n",
```

2023-04-14 11:57 UTC, jayniep-gc approved these changes

2023-04-17 10:06 UTC, payoto approved these changes
Couple of changes to the setup for PS, but the notebook looks great!

2023-04-17 10:06 UTC, payoto commented on notebooks/flan_t5_inference.ipynb
> +    "num_available_ipus=int(os.getenv(\"NUM_AVAILABLE_IPU\") or os.getenv(\"GRAPHCORE_POD_TYPE\", \"pod\")[3:] or 4)"
Looks ugly, use one or the other, and use the fact `getenv` takes a default?
```
pod_type = os.getenv("GRAPHCORE_POD_TYPE", "pod4")
num_available_ipus = int(os.getenv("NUM_AVAILABLE_IPU", pod_type[3:]))
```

or just

```
num_available_ipus = int(os.getenv("NUM_AVAILABLE_IPU", 4)
```

The two env vars are set by the same script

2023-04-17 10:12 UTC, HMellor commented on notebooks/flan_t5_inference.ipynb
> +    "num_available_ipus=int(os.getenv(\"NUM_AVAILABLE_IPU\") or os.getenv(\"GRAPHCORE_POD_TYPE\", \"pod\")[3:] or 4)"
In the guide it said that `POD_TYPE` is for optimum and `NUM_AVAILABLE_IPU` is for Paperspace, so I wanted to support both.

I didn't use the default of `getenv` because I wanted to use the default for one env var if the other was available

2023-04-17 10:17 UTC, HMellor commented on notebooks/flan_t5_inference.ipynb
> +  {
Looking at the other notebooks in https://github.com/graphcore/Graphcore-HuggingFace-fork, none of them contain a table either. Is this a table at a top of the repo?

2023-04-17 10:20 UTC, HMellor commented on notebooks/flan_t5_inference.ipynb
> +    "    max_input_length=896,\n",
This parameter might be different depending on the user's application. If we put the largest `max_input_length` in the config we upload to HF then we guarantee the worst case compile time for a new user. So these have traditionally been left out of the config.

2023-04-17 14:01 UTC, HMellor commented on notebooks/flan_t5_inference.ipynb
> +    "num_available_ipus=int(os.getenv(\"NUM_AVAILABLE_IPU\") or os.getenv(\"GRAPHCORE_POD_TYPE\", \"pod\")[3:] or 4)"
Ok, in that case I'll just use `NUM_AVAILABLE_IPU` only as that's what I really care about here

2023-05-04 09:16 UTC, jimypbr approved these changes

2023-05-04 09:31 UTC, merged