Refactor: prefix IPUConfig `ManagedAttribute`s instead of overloading user provided attributes
huggingface/optimum-graphcore pull request #366
Opened 2023-05-02 17:29 UTC by kundaMwiza

# What does this PR do?

The use of IPUConfig `ManagedAttribute`s currently involves the use of three attributes: `attribute`, `training_attribute` and `inference_attribute` (e.g. `layers_per_ipu`, `training_layers_per_ipu` and `inference_layers_per_ipu`). `attribute` is overrided internally to be a descriptor that returns `training_attribute` or `inference_attribute` depending on the `IPUConfig` mode. Since `attribute` is a descriptor, outside of the `Trainer` and `Pipeline` api, it is not guaranteed that the behaviour of the descriptor `attribute` will be consistent with the user expectation since the `IPUConfig` mode has to be set correctly.  This PR moves  `attribute` to a  descriptor `_attribute` that is handled internally, removing the need for the user to be concerned with the `IPUConfig` mode behaviour.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2023-05-02 18:32 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-graphcore/pr_366). All of your documentation changes will be reflected on that endpoint.

2023-05-03 10:21 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
>          # Get execution mode agnostic arguments
This statement is no longer true

2023-05-03 10:26 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +        self.inference_ipus_per_replica = kwargs.pop("inference_ipus_per_replica", ipus_per_replica)
```suggestion
        self.inference_layers_per_ipu = kwargs.pop("inference_layers_per_ipu", self.layers_per_ipu)
        self.inference_ipus_per_replica = kwargs.pop("inference_ipus_per_replica",len(self.inference_layers_per_ipu))
```

2023-05-03 10:28 UTC, kundaMwiza commented on optimum/graphcore/ipu_configuration.py
>          # Get execution mode agnostic arguments
Why?

2023-05-03 10:31 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +        # If matmul_proportion is a list and its length is not equal to inference_ipus_per_replica, use the
I would move this comment down 2 lines so that it immediately precedes what it is referring to

2023-05-03 10:32 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +    _device_iterations = ManagedAttribute("device_iterations")
Was this added by accident? I don't see any reference to it elsewhere in this PR

2023-05-03 10:36 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +        self._mode = value
Do we want the user to be able to set the mode this way? Writing to this property can be controlled by us using the `train()` and `eval()` methods

2023-05-03 10:38 UTC, kundaMwiza commented on optimum/graphcore/ipu_configuration.py
> +        self._mode = value
internally we use 
old_mode = self.mode
..
self.mode = old_mode

just thought its easier than conditioning on the value of old_mode

2023-05-03 10:39 UTC, kundaMwiza commented on optimum/graphcore/ipu_configuration.py
> +    _device_iterations = ManagedAttribute("device_iterations")
I added it since it is a mode based attribute even though it is not used..yet?

2023-05-03 10:44 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +            return attr
This function could be moved inside `ManagedAttribute` as a property called `full_name` and then it could be used like this:
```
raise IncompatibleIPUConfigError(
    f"Invalid values in {layers_per_ipu.full_name}. {layers_per_ipu.full_name}={layers_per_ipu}"
)
```
Instead of creating a temporary string.

2023-05-03 10:47 UTC, kundaMwiza commented on optimum/graphcore/ipu_configuration.py
> +            return attr
The name of the attribute depends on the mode

2023-05-03 10:49 UTC, HMellor commented on optimum/graphcore/modeling_utils.py
With the suggestion made in `ipu_configuration.py` the `*_mode_str` parts wouldn't be necessary

2023-05-03 10:49 UTC, HMellor requested changes
Made a few comments about suggested changes

2023-05-03 10:50 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
>          # Get execution mode agnostic arguments
Because `__init__` no longer takes mode agnostic arguments

2023-05-03 10:51 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +    _device_iterations = ManagedAttribute("device_iterations")
If it isn't going to be get or set it's addition should be delayed to a PR that implements its usage too

2023-05-03 10:53 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +        self._mode = value
Where is it use like this?

2023-05-03 10:54 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +            return attr
Exactly, and the `ManagedAttribute` knows the mode, which is how it returns the correct value. I'm suggesting we use exactly the same mechanism to return the correct name

2023-05-03 10:54 UTC, kundaMwiza commented on optimum/graphcore/ipu_configuration.py
> +        self._mode = value
For example ipu_configuration.py:_to_options

2023-05-03 11:09 UTC, kundaMwiza commented on optimum/graphcore/ipu_configuration.py
>          # Get execution mode agnostic arguments
By mode agnostic arguments do you mean what `layers_per_ipu` was previously, or arguments for parameters like `gradient_accumulation_count`?

2023-05-03 11:10 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +        self._mode = value
Ah, of course

2023-05-03 11:14 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +            return attr
Good point, so we still need to pass the mode to this function. Can we still make it a method of the `ManagedAttribute` class for DRY reasons as it already contains the `if else` logic for adding `inference_`?

2023-05-03 17:14 UTC, kundaMwiza commented on optimum/graphcore/ipu_configuration.py
> +            return attr
This would make the syntax self.ipu_config.ManagedAttribute._get_attr_name(self.ipu_config.mode, "layers_per_ipu") because `self`=`ManagedAttribute`instance cannot be passed easily to `_get_attr_name` and so the `static`/ `class` method wouldn't know which attribute is being referred to

2023-05-03 17:43 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +            return attr
Wouldn't it be `self.ipu_config.layers_per_ipu.full_name(self.ipu_config.mode)`?

2023-05-03 17:46 UTC, kundaMwiza commented on optimum/graphcore/ipu_configuration.py
> +            return attr
Each attribute access from left to right returns the attribute if it exists, so on calling `full_name(..)`, that is called on the List[int] from `_layers_per_ipu`

2023-05-03 17:49 UTC, kundaMwiza commented on optimum/graphcore/ipu_configuration.py
> +            return attr
The problem is roughly that `getattr(ipu_config, "_layers_per_ipu")` is internally replaced by `getattr(ipu_config, "_layers_per_ipu").__get__()` since `_layers_per_ipu` is a descriptor

2023-05-04 08:54 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
>          # Get execution mode agnostic arguments
Yeah originally this comment was for what `layers_per_ipu` was previously (i.e. not `training_` or `inference_`).

2023-05-04 08:55 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +            return attr
Ah of course, my mistake. You can ignore this comment

2023-05-04 09:06 UTC, HMellor commented on optimum/graphcore/ipu_configuration.py
> +        self.layers_per_ipu = kwargs.pop("layers_per_ipu", [-1])
Good spot, let's revert my suggestion

2023-05-10 15:03 UTC, jimypbr commented
I can do assignment:
```
ipu_config._ipus_per_config = 3
```
is that desired?

2023-05-10 15:11 UTC, kundaMwiza commented
> I can do assignment:
> 
> ```
> ipu_config._ipus_per_config = 3
> ```
> 
> is that desired?

@jimypbr The IPUConfig is not a frozen class that prevents users from adding new attributes? Or do you mean assignment  to managed attributes like layers_per_ipu: ipu_config._layers_per_ipu = 5? _layers_per_ipu is a private attribute so the user shouldn't be interacting with it. If we want to make sure that internally we don't use _layers_per_ipu to set the value of a training/inference attribute, that may cause complications with attributes like replication_factor which has its value overrided depending on n_ipus. However, replication_factor currently is not a ManagedAttribute..

2023-05-10 15:37 UTC, katalinic-gc approved these changes

2023-05-10 17:17 UTC, merged