Add notebook for whisper finetuning
huggingface/optimum-graphcore pull request #460
Opened 2023-07-17 15:24 UTC by katalinic-gc

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2023-07-17 15:28 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-graphcore/pr_460). All of your documentation changes will be reflected on that endpoint.

2023-07-18 07:05 UTC, jayniep-gc requested changes
Tech Docs review. General comments.

2023-07-18 07:05 UTC, jayniep-gc commented on notebooks/whisper_finetuning.ipynb
> +    "The model can be directly fine-tuned on the IPU using the `IPUSeq2SeqTrainer`. \n",
```suggestion
    "The model can be directly fine-tuned on the IPU using the `IPUSeq2SeqTrainer` class. \n",
```

2023-07-18 07:05 UTC, jayniep-gc commented on notebooks/whisper_finetuning.ipynb
> +    "For fine-tuning we place the encoder on one IPU, and the decoder on a different IPU. We then create two replicas to use all four IPUs via data-parallelism.\n",
```suggestion
    "For fine-tuning, we place the encoder on one IPU, and the decoder on a different IPU. We then create two replicas to use all four IPUs with data parallelism.\n",
```

2023-07-18 07:05 UTC, jayniep-gc commented on notebooks/whisper_finetuning.ipynb
> +    "Then we just need to pass all of this together with our datasets to the `IPUSeq2SeqTrainer` class:"
```suggestion
    "Then, we just need to pass all of this together with our datasets to the `IPUSeq2SeqTrainer` class:"
```

2023-07-18 07:05 UTC, jayniep-gc commented on notebooks/whisper_finetuning.ipynb
> +    "To gauge the improvement in WER, we run an evaluation step before finetuning."
```suggestion
    "To gauge the improvement in WER, we run an evaluation step before fine-tuning."
```

2023-07-18 07:05 UTC, jayniep-gc commented on notebooks/whisper_finetuning.ipynb
> +    "In this notebook we demonstrated how to fine-tune Whisper for multi-lingual speech recognition and transcription on the IPU. To reduce the fine-tuning time by using more than 1 replica more IPUs
```suggestion
    "In this notebook, we demonstrated how to fine-tune Whisper for multi-lingual speech recognition and transcription on the IPU. To reduce the fine-tuning time we used two replicas on a total of four IPUs. You can use even more IPUs for a greater reduction of time. On Paperspace, you can use either an IPU-POD16 or a BoW-IPU-POD16, both with 16 IPUs. Please contact Graphcore if you need assistance running on larger platforms.\n",
```

2023-07-18 10:04 UTC, katalinic-gc commented on notebooks/whisper_finetuning.ipynb
> +    "Ensure language-appropriate tokens, if any, are set for generation. The settings are overly cautious to ensure they apply correctly."
Hopefully improved

2023-07-18 10:05 UTC, katalinic-gc commented on notebooks/whisper_finetuning.ipynb
> +    "In this notebook we demonstrated how to fine-tune Whisper for multi-lingual speech recognition and transcription on the IPU. To reduce the fine-tuning time by using more than 1 replica more IPUs
We are only using one replica, so I changed it to something more aligned with your suggestion

2023-07-18 10:05 UTC, katalinic-gc commented
> Tech Docs review. General comments.

Many thanks!

2023-07-18 10:16 UTC, jayniep-gc approved these changes
Two minor tweaks, but otherwise looks good!

2023-07-18 10:16 UTC, jayniep-gc commented on notebooks/whisper_finetuning.ipynb
> +    "Lastly, we pre-process the labels by padding them with values that will be ignored during fine-tuning. This padding is to ensure tensors of static shape are provided to the model. We do this on
```suggestion
    "Lastly, we pre-process the labels by padding them with values that will be ignored during fine-tuning. This padding is to ensure tensors of static shape are provided to the model. We do this on the fly via the data collator below."
```

2023-07-18 10:16 UTC, jayniep-gc commented on notebooks/whisper_finetuning.ipynb
> +    "Ensure language-appropriate tokens, if any, are set for generation. We set them on both the `config` and the `generation_config` to ensure they are used correctly during generation."
👍

2023-07-18 10:16 UTC, jayniep-gc commented on notebooks/whisper_finetuning.ipynb
> +    "In this notebook, we demonstrated how to fine-tune Whisper for multi-lingual speech recognition and transcription on the IPU. We used a single replica on a total of four IPUs. To reduce the fine
```suggestion
    "In this notebook, we demonstrated how to fine-tune Whisper for multi-lingual speech recognition and transcription on the IPU. We used a single replica on a total of four IPUs. To reduce the fine-tuning time, more than one replica, hence more IPUs are required. On Paperspace, you can use either an IPU-POD16 or a Bow-POD16, both with 16 IPUs. Please contact Graphcore if you need assistance running on larger platforms.\n",
```

2023-07-19 12:15 UTC, payoto approved these changes
Some minor suggestions but looks good.

API wise, @katalinic-gc would there be a way to "register" different trainers for model types so that you don't have to pick the right trainer type (`TrainerSeq2Seq`). Or does this not make sense?

2023-07-19 12:15 UTC, payoto commented on notebooks/whisper_finetuning.ipynb
- Does this notebook scale with number of IPUs? If so should be in the top level table
  - After reading, doesn't seem that this does, can it scale to pod16 efficiently? If it does that could be quite nice.
- The pip install command should be `%pip install optimum-graphcore==0.7.0` no installation from source (except if this notebook only works with the main branch)
- I don't think having the arguments in one cell at the top make it very clear what you are doing, better to have them closer to first use (the dataset arguments in the same cell as the load_dataset call, this is because otherwise, to change the dataset you need to re-run two cells, when the setup is like this I often change the "input" cell, forget to run it, and wonder why my dataset hasn't changed)

2023-07-19 12:18 UTC, katalinic-gc commented
> Some minor suggestions but looks good.
> 
> API wise, @katalinic-gc would there be a way to "register" different trainers for model types so that you don't have to pick the right trainer type (`TrainerSeq2Seq`). Or does this not make sense?

That would be a non-negligible change, and we are basically just following upstream with their main `Trainer` and subclassed `TrainerSeq2Seq` classes.

2023-07-19 12:19 UTC, katalinic-gc commented on notebooks/whisper_finetuning.ipynb
> * The pip install command should be `%pip install optimum-graphcore==0.7.0` no installation from source (except if this notebook only works with the main branch)

The notebook requires https://github.com/huggingface/optimum-graphcore/pull/427, which is not in 0.7 (but will be in 0.7.1).

2023-07-19 12:23 UTC, katalinic-gc commented on notebooks/whisper_finetuning.ipynb
> Does this notebook scale with number of IPUs? If so should be in the top level table
> * After reading, doesn't seem that this does, can it scale to pod16 efficiently? If it does that could be quite nice.

Should that be indicated as a separate row in the table / through brackets? Fine-tuning will take into account `n_ipu` to replicate accordingly.

2023-07-19 17:34 UTC, merged